### ISSUE TITLE
jsoncpp issue in Debian/Ubuntu distros

### ISSUE THREAD

**Issue by ghost** [SeungheonOh/DisCpp#3]
I have trouble building DisCpp, or with the `json` library. I get an error that says I don't have the `json.h` file, and it isn't on `json`'s releases. I have also tried compiling `json` myself to see if I could get the file, but still there's only `json.hpp`.

My system is an Acer Aspire One D270; Debian 9.

**Comment by consnop** [comment]
I think what you need is ` libjsoncpp-dev`

**Comment by SeungheonOh** [comment]
https://www.reddit.com/r/unixporn/comments/cfd64p/oc_new_cli_discord_client_discpp_that_is_purely/eu9xh70?utm_source=share&utm_medium=web2x
Seems like it's the problem with apt package manager, therefore you can link then the the directory where it should be. 
Also if you are not comfortable with linking files, you can add flags to Makefile, to your directory of jsoncpp! Hope this works!

**Comment by ghost** [comment]
@zilrich 
```
root@shibe-debian:/home/geniek/Desktop# apt install libjsoncpp-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjsoncpp-dev is already the newest version (1.7.4-3).
The following packages were automatically installed and are no longer required:
[A VEEERY LONG LIST]
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@shibe-debian:/home/geniek/Desktop# 
```

**Comment by ghost** [comment]
Fixed it with `for file in $(fgrep -rl "<json/json.h>"); do sed -i "s/<json\/json.h>/<jsoncpp\/json\/json.h>/" $file; done`.
