### ISSUE TITLE
Not showing non-english symbols

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [SeungheonOh/DisCpp#5]
I can't read non-English symbols in DisCpp. That's what I see when I join my server which main language is Russian: 
![image](https://user-images.githubusercontent.com/43478602/61633120-0f67a280-ac97-11e9-8c52-ff879e2afce2.png)

**Comment by SeungheonOh** [comment]
It was basicly, planned, because some of non ascii languages have different spacing, which does ruin the spacsers. I, however, will try to fix that problem.

**Comment by SeungheonOh** [comment]
![](https://theasciicode.com.ar/american-standard-code-information-interchange/ascii-codes-table.png)

Does this have full Russian alphabets?

**Comment by SeungheonOh** [comment]
fixed in 
https://github.com/SeungheonOh/DisCpp/commit/7855acd4386b7dae6fa9360657122176f89a43ad

**Comment by SeungheonOh** [comment]
![](https://user-images.githubusercontent.com/24271442/61659668-a3cd0780-ac8d-11e9-8ed1-d53ffe3baedc.png)
